#!/bin/bash

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "A"},"price": 11200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "B"},"price": 10500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "C"},"price": 10000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "D"},"price": 10100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "E"},"price": 10700}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "F"},"price": 11200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "G"},"price": 10500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "H"},"price": 10800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-1-1","category": {"name": "상의" },"brand": {"name": "I"},"price": 11400}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "A"},"price": 5500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "B"},"price": 5900}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "C"},"price": 6200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "D"},"price": 5100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "E"},"price": 5000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "F"},"price": 7200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "G"},"price": 5800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "H"},"price": 6300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-2-1","category": {"name": "아우터" },"brand": {"name": "I"},"price": 6700}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "A"},"price": 4200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "B"},"price": 3800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "C"},"price": 3300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "D"},"price": 3000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "E"},"price": 3800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "F"},"price": 4000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "G"},"price": 3900}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "H"},"price": 3100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-3-1","category": {"name": "바지" },"brand": {"name": "I"},"price": 3200}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "A"},"price": 9000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "B"},"price": 9100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "C"},"price": 9200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "D"},"price": 9500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "E"},"price": 9900}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "F"},"price": 9300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "G"},"price": 9000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "H"},"price": 9700}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-4-1","category": {"name": "스니커즈" },"brand": {"name": "I"},"price": 9500}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "A"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "B"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "C"},"price": 2200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "D"},"price": 2500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "E"},"price": 2300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "F"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "G"},"price": 2200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "H"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-5-1","category": {"name": "가방" },"brand": {"name": "I"},"price": 2400}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "A"},"price": 1700}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "B"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "C"},"price": 1900}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "D"},"price": 1500}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "E"},"price": 1800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "F"},"price": 1600}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "G"},"price": 1700}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "H"},"price": 1600}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-6-1","category": {"name": "모자" },"brand": {"name": "I"},"price": 1700}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "A"},"price": 1800}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "B"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "C"},"price": 2200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "D"},"price": 2400}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "E"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "F"},"price": 2300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "G"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "H"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-7-1","category": {"name": "양말" },"brand": {"name": "I"},"price": 1700}'

curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-A-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "A"},"price": 2300}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-B-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "B"},"price": 2200}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-C-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "C"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-D-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "D"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-E-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "E"},"price": 2100}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-F-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "F"},"price": 1900}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-G-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "G"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-H-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "H"},"price": 2000}'
curl -X 'POST' 'http://localhost/api/v1/product/add' -H 'Content-Type: application/json' -d '{"name": "BRD-I-CTGR-8-1","category": {"name": "액세서리" },"brand": {"name": "I"},"price": 2400}'